#include<stdio.h>
main()
{
	printf("--------\n");
	printf("|\t|\n");
	printf("S\t|\n");
	printf("u\t|\n");
	printf("D\t|\n");
	printf("H\t|\n");
	printf("A\t|\n");
	printf("N\t|\n");
	printf("S\t|\n");
	printf("U\t|\n");
	printf("|\t|\n");
	printf("---------\n");
}
